local plr = game.Players.LocalPlayer

local f = script.Parent:WaitForChild("Frame")
pcall(function() f.lblHey.Text = "Hey "..plr.Name.."!" end)
f:TweenPosition(UDim2.new(.375,0,.325,0))
coroutine.resume(coroutine.create(function()
	workspace.Remotes.CtoS.GiveItem:FireServer(2,"Beta Tester")
	workspace.Remotes.CtoS.GiveItem:FireServer(2,"Crimson Catseye")
	workspace.Remotes.CtoS.GiveItem:FireServer(2,"Doge")
	workspace.Remotes.CtoS.GiveItem:FireServer(2,"Crystal Epic")
	workspace.Remotes.CtoS.GiveItem:FireServer(2,"Circle O Blue Fire")
	workspace.Remotes.CtoS.GiveItem:FireServer(4,"Illuminati")
	workspace.Remotes.CtoS.GiveItem:FireServer(4,"Stacks of Dollars")
	workspace.Remotes.CtoS.GiveItem:FireServer(4,"Beta")
	workspace.Remotes.CtoS.GiveItem:FireServer(4,"Epic Face")
	workspace.Remotes.CtoS.GiveCoins:InvokeServer(1337)
end))
wait(8)
f:TweenPosition(UDim2.new(1,0,1,0))
wait(1.337)
script.Parent:Destroy()
